spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_name?useSSL=false
    username: dbuser
    password: dbpass
  jpa:
    database: mysql
    show-sql: true
    properties:
      javax: 
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: dashboard_data.sql

      hibernate:
        ddl-auto: create-drop
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect